services:
  postgres:
    image: postgres:latest
    container_name: gosus_postgres
    restart: always
    environment:
      POSTGRES_DB: gosus-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: "UTC-4"
    ports:
      - 5432:5432
    command: -p 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gosus_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: gosus@gosus.com
      PGADMIN_DEFAULT_PASSWORD: gosus
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgadmin-data:
  postgres-data:
  